# Generated by Django 5.0.1 on 2024-02-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
