# Generated by Django 5.0.1 on 2024-02-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_management', '0004_alter_project_task_project_alter_project_task_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectid',
            new_name='projectId',
        ),
    ]
