# Generated by Django 5.0.1 on 2024-02-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_management', '0005_rename_projectid_project_projectid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_task',
            new_name='ProjectTask',
        ),
    ]
