# Generated by Django 5.0.1 on 2024-02-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_management', '0006_rename_project_task_projecttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectTask', to='project_task_management.project'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectTask', to='project_task_management.task'),
        ),
    ]
