# Generated by Django 5.0.1 on 2024-02-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_management', '0007_alter_projecttask_project_alter_projecttask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
