# Generated by Django 5.0.1 on 2024-02-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_management', '0008_remove_projecttask_project_remove_projecttask_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='project_task_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectTask', to='project_task_management.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectTask', to='project_task_management.task')),
            ],
        ),
    ]
