# Generated by Django 5.0.1 on 2024-02-03 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_management', '0009_project_task_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project_task_management.project'),
        ),
        migrations.DeleteModel(
            name='ProjectTask',
        ),
    ]
