# Generated by Django 5.0.1 on 2024-02-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_management', '0010_task_project_delete_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO DO', 'To Do'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TO DO', max_length=20),
        ),
    ]
