# Generated by Django 5.0.1 on 2024-02-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_management', '0011_task_duedate_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
    ]
