# Generated by Django 5.0.1 on 2024-02-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_task_management', '0012_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE')], default='TODO', max_length=20),
        ),
    ]
